---
title: "Resume"
output: html_document
hidedate: true
hiderelated: true
hidediscus: true
---
AMANDA HASSELL
amanda.hassell@utexas.edu

COLLEGE EDUCATION
University of Texas/College of Natural Sciences, BS expected Spring 2021
Major: B.S. Human Biology (Pre-Dental)
GPA: 3.988 
DAT Score: 23 AA

Awards:
College of Natural Sciences Scholar, Spring 2020 & Spring 2021
College of Natural Sciences Second Year Excellence Award, Spring 2019

Extracurricular Activities & Campus Involvement: 	
Texas Pre-Dental Society Distinguished Member, Spring 2019 – present
	- Served on the Philanthropy Committee, Spring 2019
Peer Led Undergraduate Studying Facilitator for General Biochemistry at UT Austin, Fall 2019
Global Medical Training Member, Fall 2017 – Fall 2019
Chi Omega Sorority Member, Fall 2017 – present

Community Service: 
Manos De Cristo Weekly Volunteer, Spring 2019 — present
	- Work in the sterilization room of Manos de Cristo, a low-cost dental clinic in Austin, 			TX	
Global Medical Training Volunteer, Peru, June 2019 
	- Assisted dentists in Peru for one week in providing free dental care to local 				communities and helped educate citizens about proper daily oral hygiene

Employment:
Undergraduate Teaching Assistant for Human Microscopic and Gross Anatomy at UT Austin, Spring 2020